name = "GenSlam"
uuid = "921d89da-470c-4139-990e-345fceaa5d1a"
authors = ["Austin Garrett <agarret7@mit.edu>"]
version = "0.1.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
GenDirectionalStats = "85d806fb-b5ca-4d38-9c94-d1c1a6747d55"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PoseComposition = "0a8ab332-79e8-43e0-a313-949ce1168071"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
